FROM python:3.12-slim

WORKDIR /backend

COPY requirements.txt .

# Remove todo cache do pip e instala dependências limpas
RUN pip cache purge \
    && pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]